name: kam_point
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  # http: ^0.13.5
  # image_picker: ^0.8.6+1
  # opencv_4: ^1.0.0
  # path_provider: ^2.0.12
    
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/game_page_image.jpg
    - assets/icons/camera_icon_white.png
    - assets/icons/camera_icon_nav.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
  
    